{{- if .Values.fider.legalPages.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fider.fullname" . }}-legal-configmap
  labels:
    {{- include "fider.labels" . | nindent 4 }}
data:
  terms.md: |-
{{ .Values.fider.legal.terms | indent 4 }}
  privacy.md: |-
{{ .Values.fider.legal.privacy | indent 4 }}
{{- end }}