{{- if .Values.fider.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fider.fullname" . }}-env-secrets
  labels:
    {{- include "fider.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.fider.secretEnv }}
  {{ $key }}: {{- $value | b64enc | indent 2 }}
  {{- end }}
{{- end }}
