package models

// Country is a valid country within Fider
type Country struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// GetAllCountries returns a list of all known countries
func GetAllCountries() []*Country {
	return []*Country{
		&Country{Code: "US", Name: ""},
		&Country{Code: "AF", Name: "Afghanistan"},
		&Country{Code: "AX", Name: "Åland Islands"},
		&Country{Code: "AL", Name: "Albania"},
		&Country{Code: "DZ", Name: "Algeria"},
		&Country{Code: "AS", Name: "American Samoa"},
		&Country{Code: "AD", Name: "Andorra"},
		&Country{Code: "AO", Name: "Angola"},
		&Country{Code: "AI", Name: "Anguilla"},
		&Country{Code: "AQ", Name: "Antarctica"},
		&Country{Code: "AG", Name: "Antigua and Barbuda"},
		&Country{Code: "AR", Name: "Argentina"},
		&Country{Code: "AM", Name: "Armenia"},
		&Country{Code: "AW", Name: "Aruba"},
		&Country{Code: "AU", Name: "Australia"},
		&Country{Code: "AT", Name: "Austria"},
		&Country{Code: "AZ", Name: "Azerbaijan"},
		&Country{Code: "BS", Name: "Bahamas"},
		&Country{Code: "BH", Name: "Bahrain"},
		&Country{Code: "BD", Name: "Bangladesh"},
		&Country{Code: "BB", Name: "Barbados"},
		&Country{Code: "BY", Name: "Belarus"},
		&Country{Code: "BE", Name: "Belgium"},
		&Country{Code: "BZ", Name: "Belize"},
		&Country{Code: "BJ", Name: "Benin"},
		&Country{Code: "BM", Name: "Bermuda"},
		&Country{Code: "BT", Name: "Bhutan"},
		&Country{Code: "BO", Name: "Bolivia, Plurinational State of"},
		&Country{Code: "BQ", Name: "Bonaire, Sint Eustatius and Saba"},
		&Country{Code: "BA", Name: "Bosnia and Herzegovina"},
		&Country{Code: "BW", Name: "Botswana"},
		&Country{Code: "BV", Name: "Bouvet Island"},
		&Country{Code: "BR", Name: "Brazil"},
		&Country{Code: "IO", Name: "British Indian Ocean Territory"},
		&Country{Code: "BN", Name: "Brunei Darussalam"},
		&Country{Code: "BG", Name: "Bulgaria"},
		&Country{Code: "BF", Name: "Burkina Faso"},
		&Country{Code: "BI", Name: "Burundi"},
		&Country{Code: "KH", Name: "Cambodia"},
		&Country{Code: "CM", Name: "Cameroon"},
		&Country{Code: "CA", Name: "Canada"},
		&Country{Code: "CV", Name: "Cape Verde"},
		&Country{Code: "KY", Name: "Cayman Islands"},
		&Country{Code: "CF", Name: "Central African Republic"},
		&Country{Code: "TD", Name: "Chad"},
		&Country{Code: "CL", Name: "Chile"},
		&Country{Code: "CN", Name: "China"},
		&Country{Code: "CX", Name: "Christmas Island"},
		&Country{Code: "CC", Name: "Cocos (Keeling) Islands"},
		&Country{Code: "CO", Name: "Colombia"},
		&Country{Code: "KM", Name: "Comoros"},
		&Country{Code: "CG", Name: "Congo"},
		&Country{Code: "CD", Name: "Congo, the Democratic Republic of the"},
		&Country{Code: "CK", Name: "Cook Islands"},
		&Country{Code: "CR", Name: "Costa Rica"},
		&Country{Code: "CI", Name: "Côte d'Ivoire"},
		&Country{Code: "HR", Name: "Croatia"},
		&Country{Code: "CU", Name: "Cuba"},
		&Country{Code: "CW", Name: "Curaçao"},
		&Country{Code: "CY", Name: "Cyprus"},
		&Country{Code: "CZ", Name: "Czech Republic"},
		&Country{Code: "DK", Name: "Denmark"},
		&Country{Code: "DJ", Name: "Djibouti"},
		&Country{Code: "DM", Name: "Dominica"},
		&Country{Code: "DO", Name: "Dominican Republic"},
		&Country{Code: "EC", Name: "Ecuador"},
		&Country{Code: "EG", Name: "Egypt"},
		&Country{Code: "SV", Name: "El Salvador"},
		&Country{Code: "GQ", Name: "Equatorial Guinea"},
		&Country{Code: "ER", Name: "Eritrea"},
		&Country{Code: "EE", Name: "Estonia"},
		&Country{Code: "ET", Name: "Ethiopia"},
		&Country{Code: "FK", Name: "Falkland Islands (Malvinas)"},
		&Country{Code: "FO", Name: "Faroe Islands"},
		&Country{Code: "FJ", Name: "Fiji"},
		&Country{Code: "FI", Name: "Finland"},
		&Country{Code: "FR", Name: "France"},
		&Country{Code: "GF", Name: "French Guiana"},
		&Country{Code: "PF", Name: "French Polynesia"},
		&Country{Code: "TF", Name: "French Southern Territories"},
		&Country{Code: "GA", Name: "Gabon"},
		&Country{Code: "GM", Name: "Gambia"},
		&Country{Code: "GE", Name: "Georgia"},
		&Country{Code: "DE", Name: "Germany"},
		&Country{Code: "GH", Name: "Ghana"},
		&Country{Code: "GI", Name: "Gibraltar"},
		&Country{Code: "GR", Name: "Greece"},
		&Country{Code: "GL", Name: "Greenland"},
		&Country{Code: "GD", Name: "Grenada"},
		&Country{Code: "GP", Name: "Guadeloupe"},
		&Country{Code: "GU", Name: "Guam"},
		&Country{Code: "GT", Name: "Guatemala"},
		&Country{Code: "GG", Name: "Guernsey"},
		&Country{Code: "GN", Name: "Guinea"},
		&Country{Code: "GW", Name: "Guinea-Bissau"},
		&Country{Code: "GY", Name: "Guyana"},
		&Country{Code: "HT", Name: "Haiti"},
		&Country{Code: "HM", Name: "Heard Island and McDonald Islands"},
		&Country{Code: "VA", Name: "Holy See (Vatican City State)"},
		&Country{Code: "HN", Name: "Honduras"},
		&Country{Code: "HK", Name: "Hong Kong"},
		&Country{Code: "HU", Name: "Hungary"},
		&Country{Code: "IS", Name: "Iceland"},
		&Country{Code: "IN", Name: "India"},
		&Country{Code: "ID", Name: "Indonesia"},
		&Country{Code: "IR", Name: "Iran, Islamic Republic of"},
		&Country{Code: "IQ", Name: "Iraq"},
		&Country{Code: "IE", Name: "Ireland"},
		&Country{Code: "IM", Name: "Isle of Man"},
		&Country{Code: "IL", Name: "Israel"},
		&Country{Code: "IT", Name: "Italy"},
		&Country{Code: "JM", Name: "Jamaica"},
		&Country{Code: "JP", Name: "Japan"},
		&Country{Code: "JE", Name: "Jersey"},
		&Country{Code: "JO", Name: "Jordan"},
		&Country{Code: "KZ", Name: "Kazakhstan"},
		&Country{Code: "KE", Name: "Kenya"},
		&Country{Code: "KI", Name: "Kiribati"},
		&Country{Code: "KP", Name: "Korea, Democratic People's Republic of"},
		&Country{Code: "KR", Name: "Korea, Republic of"},
		&Country{Code: "KW", Name: "Kuwait"},
		&Country{Code: "KG", Name: "Kyrgyzstan"},
		&Country{Code: "LA", Name: "Lao People's Democratic Republic"},
		&Country{Code: "LV", Name: "Latvia"},
		&Country{Code: "LB", Name: "Lebanon"},
		&Country{Code: "LS", Name: "Lesotho"},
		&Country{Code: "LR", Name: "Liberia"},
		&Country{Code: "LY", Name: "Libya"},
		&Country{Code: "LI", Name: "Liechtenstein"},
		&Country{Code: "LT", Name: "Lithuania"},
		&Country{Code: "LU", Name: "Luxembourg"},
		&Country{Code: "MO", Name: "Macao"},
		&Country{Code: "MK", Name: "Macedonia, the former Yugoslav Republic of"},
		&Country{Code: "MG", Name: "Madagascar"},
		&Country{Code: "MW", Name: "Malawi"},
		&Country{Code: "MY", Name: "Malaysia"},
		&Country{Code: "MV", Name: "Maldives"},
		&Country{Code: "ML", Name: "Mali"},
		&Country{Code: "MT", Name: "Malta"},
		&Country{Code: "MH", Name: "Marshall Islands"},
		&Country{Code: "MQ", Name: "Martinique"},
		&Country{Code: "MR", Name: "Mauritania"},
		&Country{Code: "MU", Name: "Mauritius"},
		&Country{Code: "YT", Name: "Mayotte"},
		&Country{Code: "MX", Name: "Mexico"},
		&Country{Code: "FM", Name: "Micronesia, Federated States of"},
		&Country{Code: "MD", Name: "Moldova, Republic of"},
		&Country{Code: "MC", Name: "Monaco"},
		&Country{Code: "MN", Name: "Mongolia"},
		&Country{Code: "ME", Name: "Montenegro"},
		&Country{Code: "MS", Name: "Montserrat"},
		&Country{Code: "MA", Name: "Morocco"},
		&Country{Code: "MZ", Name: "Mozambique"},
		&Country{Code: "MM", Name: "Myanmar"},
		&Country{Code: "NA", Name: "Namibia"},
		&Country{Code: "NR", Name: "Nauru"},
		&Country{Code: "NP", Name: "Nepal"},
		&Country{Code: "NL", Name: "Netherlands"},
		&Country{Code: "NC", Name: "New Caledonia"},
		&Country{Code: "NZ", Name: "New Zealand"},
		&Country{Code: "NI", Name: "Nicaragua"},
		&Country{Code: "NE", Name: "Niger"},
		&Country{Code: "NG", Name: "Nigeria"},
		&Country{Code: "NU", Name: "Niue"},
		&Country{Code: "NF", Name: "Norfolk Island"},
		&Country{Code: "MP", Name: "Northern Mariana Islands"},
		&Country{Code: "NO", Name: "Norway"},
		&Country{Code: "OM", Name: "Oman"},
		&Country{Code: "PK", Name: "Pakistan"},
		&Country{Code: "PW", Name: "Palau"},
		&Country{Code: "PS", Name: "Palestinian Territory, Occupied"},
		&Country{Code: "PA", Name: "Panama"},
		&Country{Code: "PG", Name: "Papua New Guinea"},
		&Country{Code: "PY", Name: "Paraguay"},
		&Country{Code: "PE", Name: "Peru"},
		&Country{Code: "PH", Name: "Philippines"},
		&Country{Code: "PN", Name: "Pitcairn"},
		&Country{Code: "PL", Name: "Poland"},
		&Country{Code: "PT", Name: "Portugal"},
		&Country{Code: "PR", Name: "Puerto Rico"},
		&Country{Code: "QA", Name: "Qatar"},
		&Country{Code: "RE", Name: "Réunion"},
		&Country{Code: "RO", Name: "Romania"},
		&Country{Code: "RU", Name: "Russian Federation"},
		&Country{Code: "RW", Name: "Rwanda"},
		&Country{Code: "BL", Name: "Saint Barthélemy"},
		&Country{Code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha"},
		&Country{Code: "KN", Name: "Saint Kitts and Nevis"},
		&Country{Code: "LC", Name: "Saint Lucia"},
		&Country{Code: "MF", Name: "Saint Martin (French part)"},
		&Country{Code: "PM", Name: "Saint Pierre and Miquelon"},
		&Country{Code: "VC", Name: "Saint Vincent and the Grenadines"},
		&Country{Code: "WS", Name: "Samoa"},
		&Country{Code: "SM", Name: "San Marino"},
		&Country{Code: "ST", Name: "Sao Tome and Principe"},
		&Country{Code: "SA", Name: "Saudi Arabia"},
		&Country{Code: "SN", Name: "Senegal"},
		&Country{Code: "RS", Name: "Serbia"},
		&Country{Code: "SC", Name: "Seychelles"},
		&Country{Code: "SL", Name: "Sierra Leone"},
		&Country{Code: "SG", Name: "Singapore"},
		&Country{Code: "SX", Name: "Sint Maarten (Dutch part)"},
		&Country{Code: "SK", Name: "Slovakia"},
		&Country{Code: "SI", Name: "Slovenia"},
		&Country{Code: "SB", Name: "Solomon Islands"},
		&Country{Code: "SO", Name: "Somalia"},
		&Country{Code: "ZA", Name: "South Africa"},
		&Country{Code: "GS", Name: "South Georgia and the South Sandwich Islands"},
		&Country{Code: "SS", Name: "South Sudan"},
		&Country{Code: "ES", Name: "Spain"},
		&Country{Code: "LK", Name: "Sri Lanka"},
		&Country{Code: "SD", Name: "Sudan"},
		&Country{Code: "SR", Name: "Suriname"},
		&Country{Code: "SJ", Name: "Svalbard and Jan Mayen"},
		&Country{Code: "SZ", Name: "Swaziland"},
		&Country{Code: "SE", Name: "Sweden"},
		&Country{Code: "CH", Name: "Switzerland"},
		&Country{Code: "SY", Name: "Syrian Arab Republic"},
		&Country{Code: "TW", Name: "Taiwan, Province of China"},
		&Country{Code: "TJ", Name: "Tajikistan"},
		&Country{Code: "TZ", Name: "Tanzania, United Republic of"},
		&Country{Code: "TH", Name: "Thailand"},
		&Country{Code: "TL", Name: "Timor-Leste"},
		&Country{Code: "TG", Name: "Togo"},
		&Country{Code: "TK", Name: "Tokelau"},
		&Country{Code: "TO", Name: "Tonga"},
		&Country{Code: "TT", Name: "Trinidad and Tobago"},
		&Country{Code: "TN", Name: "Tunisia"},
		&Country{Code: "TR", Name: "Turkey"},
		&Country{Code: "TM", Name: "Turkmenistan"},
		&Country{Code: "TC", Name: "Turks and Caicos Islands"},
		&Country{Code: "TV", Name: "Tuvalu"},
		&Country{Code: "UG", Name: "Uganda"},
		&Country{Code: "UA", Name: "Ukraine"},
		&Country{Code: "AE", Name: "United Arab Emirates"},
		&Country{Code: "GB", Name: "United Kingdom"},
		&Country{Code: "US", Name: "United States"},
		&Country{Code: "UM", Name: "United States Minor Outlying Islands"},
		&Country{Code: "UY", Name: "Uruguay"},
		&Country{Code: "UZ", Name: "Uzbekistan"},
		&Country{Code: "VU", Name: "Vanuatu"},
		&Country{Code: "VE", Name: "Venezuela, Bolivarian Republic of"},
		&Country{Code: "VN", Name: "Viet Nam"},
		&Country{Code: "VG", Name: "Virgin Islands, British"},
		&Country{Code: "VI", Name: "Virgin Islands, U.S."},
		&Country{Code: "WF", Name: "Wallis and Futuna"},
		&Country{Code: "EH", Name: "Western Sahara"},
		&Country{Code: "YE", Name: "Yemen"},
		&Country{Code: "ZM", Name: "Zambia"},
		&Country{Code: "ZW", Name: "Zimbabwe"},
	}
}
