name: publish

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: build and push docker image (pull_request)
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          build-args: COMMITHASH=${{ github.event.workflow_run.head_sha }}
          platforms: linux/amd64,linux/arm64/v8
          tags: getfider/fider:PR_${{ github.event.workflow_run.pull_requests[0].number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push docker image (push)
        if: ${{ github.event.workflow_run.event == 'push' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          build-args: COMMITHASH=${{ github.event.workflow_run.head_sha }}
          platforms: linux/amd64,linux/arm64/v8
          tags: getfider/fider:SHA_${{ github.event.workflow_run.head_sha }},getfider/fider:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
